#!/bin/env python3

import sys
import os
from dataclasses import dataclass

@dataclass
class Commit:
  timestamp: str
  origin: str
  hash: str
  message: str

  def __lt__(self, other):
    return self.timestamp < other.timestamp

  def __str__(self):
    return f"\"{self.hash}\" {self.origin:<25} # {self.timestamp} - {self.message}"


class CommitList:

  def __init__(self, log_filenames):
    self.__commits = {} 
    self.__indexes = {}
    self.latest_origin = None

    for i in log_filenames:
      origin = os.path.splitext(os.path.basename(i))[0]
      lines = open(i, "r").readlines()
      lines = [j.strip().split(" ") for j in lines if j]
      lines = reversed(lines)
      self.__commits[origin] = [Commit(timestamp=j[0], hash=j[1], message=" ".join(j[2:]).strip("\""), origin=origin) for j in lines]
      self.__indexes[origin] = 0

  @property
  def origins(self):
    return self.__commits.keys()

  def get_next_commit(self) -> Commit:
    current_commits = []
    for i_origin, i_commits in self.__commits.items():
      index = self.__indexes[i_origin]
      if index >= len(i_commits):
        continue
      current_commits.append(i_commits[index])
    if not current_commits:
      return None
    result = min(current_commits)
    self.__indexes[result.origin] += 1
    return result


SCRIPT_TEMPLATE="""#!/bin/bash
# Automatically generated by monorepo.py

set -e

MONOREPO_ORIGINS="__ORIGINS__"

cd target
source ../monorepo.lib.bash
monorepo__initialization main

"""

commit_list = CommitList(sys.argv[1:])
print(SCRIPT_TEMPLATE.replace("__ORIGINS__", " ".join(commit_list.origins)))

loop_count = 0
loop_max = 1000000
merge_count = 0
merge_max = 1000000

current_commit = None
while loop_count < loop_max and merge_count < merge_max:
  next_commit = commit_list.get_next_commit()
  if not next_commit:
    break
  if current_commit is not None:
    if current_commit.origin != next_commit.origin:
      merge_count += 1
      print(f"monorepo__rebase_it {current_commit}")
  current_commit = next_commit
  loop_count += 1
print(f"monorepo__rebase_it {current_commit}")

print("""
monorepo__cleanup
""")
