#!/bin/bash
# Automatically generated by monorepo.py

set -e

MONOREPO_ORIGINS="monorepo__tfmodules_ami_build monorepo__tfmodules_auto_deploy monorepo__tfmodules_autoscaling_group monorepo__tfmodules_cloudwatch_agent_conf monorepo__tfmodules_cloudwatch_alarms monorepo__tfmodules_cloudwatch monorepo__tfmodules_cloudwatch_slack_notifications monorepo__tfmodules_database monorepo__tfmodules_deployment monorepo__tfmodules_ec2_alerts monorepo__tfmodules_ecs_cluster monorepo__tfmodules_ecs_service monorepo__tfmodules_ecs_taskdef monorepo__tfmodules_efs monorepo__tfmodules_flower monorepo__tfmodules_ftp monorepo__tfmodules_iam_access_role monorepo__tfmodules_iam monorepo__tfmodules_iam_shell_role monorepo__tfmodules_iam_terraform_role monorepo__tfmodules_instance monorepo__tfmodules_load_balancer monorepo__tfmodules_mi_iam_roles monorepo__tfmodules_newrelic_load_balancer_logs monorepo__tfmodules_newrelic_stream monorepo__tfmodules_redash monorepo__tfmodules_redis monorepo__tfmodules_s3_bucket monorepo__tfmodules_ssm_user monorepo__tfmodules_static_website"

cd target
source ../monorepo.lib.bash
monorepo__initialization main


monorepo__rebase_it "b382e62" monorepo__tfmodules_deployment # 2019-07-24T22:01:54+02:00 - Fix pi deployment group name
monorepo__rebase_it "1115243" monorepo__tfmodules_iam_access_role # 2019-07-26T12:25:11+02:00 - Merge branch 'master' of gitlab.com:motoinsight/infra/tf_modules/iam_access_role
monorepo__rebase_it "cf5cee2" monorepo__tfmodules_autoscaling_group # 2019-07-30T09:43:41+00:00 - Initial commit
monorepo__rebase_it "ded43ce" monorepo__tfmodules_database # 2019-08-05T06:56:56+00:00 - Initial commit
monorepo__rebase_it "ca7a653" monorepo__tfmodules_redis # 2019-08-07T03:54:31+00:00 - Initial commit
monorepo__rebase_it "6e78f9b" monorepo__tfmodules_load_balancer # 2019-08-07T10:07:32+00:00 - Initial commit
monorepo__rebase_it "4cde33e" monorepo__tfmodules_iam_access_role # 2019-08-12T10:47:11+00:00 - Merge branch 'infra_600' into 'master'
monorepo__rebase_it "3a28b23" monorepo__tfmodules_iam_shell_role # 2019-08-16T16:27:20+02:00 - More permissions
monorepo__rebase_it "7bbba92" monorepo__tfmodules_redis # 2019-09-05T07:13:16+00:00 - Merge branch 'infra_607' into 'master'
monorepo__rebase_it "75af240" monorepo__tfmodules_database # 2019-09-05T07:17:07+00:00 - Merge branch 'infra_607' into 'master'
monorepo__rebase_it "3e0b0b0" monorepo__tfmodules_autoscaling_group # 2019-09-05T07:19:03+00:00 - Merge branch 'infra_607' into 'master'
monorepo__rebase_it "5a6df33" monorepo__tfmodules_deployment # 2019-09-05T07:20:46+00:00 - Merge branch 'infra_607' into 'master'
monorepo__rebase_it "e3ad5f5" monorepo__tfmodules_load_balancer # 2019-09-20T21:11:19+02:00 - Fix name of target group
monorepo__rebase_it "7d9adf3" monorepo__tfmodules_deployment # 2019-10-02T10:59:04+00:00 - Merge branch 'infra_745' into 'master'
monorepo__rebase_it "e6c207e" monorepo__tfmodules_load_balancer # 2019-10-17T12:11:09+00:00 - Merge branch 'infra_759' into 'master'
monorepo__rebase_it "929492b" monorepo__tfmodules_database # 2019-10-21T07:53:21+02:00 - Ignore snapshot identifier
monorepo__rebase_it "398dd87" monorepo__tfmodules_deployment # 2019-10-31T17:05:05+01:00 - Update production message for GAUS
monorepo__rebase_it "35624a9" monorepo__tfmodules_load_balancer # 2019-12-16T12:52:04+01:00 - INFRA-875: Test
monorepo__rebase_it "7269270" monorepo__tfmodules_autoscaling_group # 2019-12-18T06:23:10+00:00 - Merge branch 'infra_758' into 'master'
monorepo__rebase_it "ad2e6a1" monorepo__tfmodules_deployment # 2019-12-20T19:43:58+01:00 - Update code
monorepo__rebase_it "0a4eaa3" monorepo__tfmodules_autoscaling_group # 2019-12-23T18:14:26+01:00 - only 64 chars limit
monorepo__rebase_it "9393753" monorepo__tfmodules_deployment # 2020-01-28T20:19:56+01:00 - Update AUDI settings
monorepo__rebase_it "d98a72d" monorepo__tfmodules_database # 2020-02-18T09:21:13+01:00 - Remove deprecated syntax while changing to terraform 0.12.20
monorepo__rebase_it "295464b" monorepo__tfmodules_deployment # 2020-02-18T09:22:11+01:00 - Remove deprecated syntax while changing to terraform 0.12.20
monorepo__rebase_it "a14284f" monorepo__tfmodules_cloudwatch_slack_notifications # 2020-02-27T15:08:56+01:00 - INFRA-956: Added new comment on internal issues sns
monorepo__rebase_it "caaf3c2" monorepo__tfmodules_load_balancer # 2020-03-02T14:33:34+01:00 - INFRA-957: Added output variable with load balancer name for cloudwatch alerts purposes
monorepo__rebase_it "0690582" monorepo__tfmodules_database # 2020-03-03T13:09:00+00:00 - Merge branch 'infra_951' into 'master'
monorepo__rebase_it "f9bd253" monorepo__tfmodules_cloudwatch_slack_notifications # 2020-03-03T15:42:01+01:00 - INFRA-956: Code review changes
monorepo__rebase_it "d2f9c80" monorepo__tfmodules_load_balancer # 2020-03-03T16:14:58+01:00 - INFRA-957: Updated outputs descriptions
monorepo__rebase_it "fe8a9d9" monorepo__tfmodules_cloudwatch_slack_notifications # 2020-03-03T22:27:03+01:00 - INFRA-956: Post code review fixes
monorepo__rebase_it "2a3b40a" monorepo__tfmodules_deployment # 2020-03-20T07:32:07+00:00 - Merge branch 'infra_963' into 'master'
monorepo__rebase_it "58b4b2d" monorepo__tfmodules_autoscaling_group # 2020-03-24T15:13:47+01:00 - INFRA-962: Added support for user_data with cloudwatch agent configuration
monorepo__rebase_it "b3b15fb" monorepo__tfmodules_database # 2020-03-25T07:18:24+00:00 - Merge branch 'infra_974' into 'master'
monorepo__rebase_it "dcaf1d5" monorepo__tfmodules_autoscaling_group # 2020-04-01T17:30:13+02:00 - INFRA-962: Removed the policy for cloudwatch put metric alarm
monorepo__rebase_it "a76a6c6" monorepo__tfmodules_cloudwatch_slack_notifications # 2020-04-02T19:30:30+02:00 - INFRA-956: sns should be accessed via count.index
monorepo__rebase_it "b1ebc89" monorepo__tfmodules_load_balancer # 2020-04-03T11:11:36+02:00 - INFRA-957: output aws_lb_name should look up name instead of id
monorepo__rebase_it "da5e38c" monorepo__tfmodules_autoscaling_group # 2020-04-07T14:26:09+02:00 - INFRA-962: Removed providers because terraform validate has a bug when provider is not set
monorepo__rebase_it "a0c187d" monorepo__tfmodules_cloudwatch_slack_notifications # 2020-04-08T19:18:57+02:00 - INFRA-988: Internal alarm should go off when there are errors
monorepo__rebase_it "c2db096" monorepo__tfmodules_database # 2020-04-10T12:26:15+02:00 - Add threshold variables for RDS alerts
monorepo__rebase_it "0a5a147" monorepo__tfmodules_deployment # 2020-04-20T12:58:29+02:00 - INFRA-985: Add polestar to lambda
monorepo__rebase_it "96bc7e4" monorepo__tfmodules_autoscaling_group # 2020-05-04T12:56:38+02:00 - Merge branch 'infra_983' of gitlab.com:motoinsight/infra/tf_modules/autoscaling_group
monorepo__rebase_it "5b9dd60" monorepo__tfmodules_iam_terraform_role # 2020-05-13T12:38:32+02:00 - Terraform Role Initial
monorepo__rebase_it "a70f7c8" monorepo__tfmodules_iam_access_role # 2020-05-13T13:37:11+02:00 - Update formating
monorepo__rebase_it "7bd47f1" monorepo__tfmodules_iam_terraform_role # 2020-05-13T13:38:34+02:00 - Update formating
monorepo__rebase_it "4047973" monorepo__tfmodules_load_balancer # 2020-05-27T13:30:52+02:00 - Remove priority
monorepo__rebase_it "60aafeb" monorepo__tfmodules_autoscaling_group # 2020-06-12T09:07:36+02:00 - Add possibilty to not create default scaling policies
monorepo__rebase_it "60fae22" monorepo__tfmodules_deployment # 2020-08-06T11:19:06+02:00 - Add notifications
monorepo__rebase_it "2a1a7b1" monorepo__tfmodules_cloudwatch # 2020-09-10T09:04:06+02:00 - Initial commit
monorepo__rebase_it "647467b" monorepo__tfmodules_cloudwatch_agent_conf # 2020-09-11T13:39:57+02:00 - cloudwatch configuration agent
monorepo__rebase_it "9c67eee" monorepo__tfmodules_cloudwatch # 2020-09-22T10:46:02+02:00 - fix count usage
monorepo__rebase_it "942cbac" monorepo__tfmodules_deployment # 2020-09-25T15:38:18+02:00 - Update release channel
monorepo__rebase_it "4a0fac4" monorepo__tfmodules_static_website # 2020-09-29T13:08:30+02:00 - Allow cert different than domain
monorepo__rebase_it "394e9b7" monorepo__tfmodules_redis # 2020-10-08T20:13:28+02:00 - Remove parameter group name
monorepo__rebase_it "71205c4" monorepo__tfmodules_load_balancer # 2020-10-13T10:48:43+00:00 - Merge branch 'infra_1187' into 'master'
monorepo__rebase_it "e692781" monorepo__tfmodules_cloudwatch_agent_conf # 2020-10-13T12:37:48-03:00 - IMP: Remove deprecated syntax.
monorepo__rebase_it "15a5941" monorepo__tfmodules_cloudwatch # 2020-10-13T12:58:44+02:00 - remove deprecated syntax
monorepo__rebase_it "642f0f3" monorepo__tfmodules_cloudwatch_slack_notifications # 2020-10-17T17:09:48+05:30 - Add gitignore
monorepo__rebase_it "33da10d" monorepo__tfmodules_database # 2020-10-17T22:07:14+05:30 - Add gitignore
monorepo__rebase_it "5e563ea" monorepo__tfmodules_deployment # 2020-10-19T13:07:26+05:30 - Add gitignore
monorepo__rebase_it "a589602" monorepo__tfmodules_autoscaling_group # 2020-10-19T13:27:21+05:30 - Add gitignore
monorepo__rebase_it "6558507" monorepo__tfmodules_iam_access_role # 2020-10-19T13:31:20+05:30 - Add gitignore
monorepo__rebase_it "3195089" monorepo__tfmodules_iam_shell_role # 2020-10-19T13:32:34+05:30 - Add gitignore
monorepo__rebase_it "2465a93" monorepo__tfmodules_iam_terraform_role # 2020-10-19T13:33:53+05:30 - Add gitignore
monorepo__rebase_it "1515115" monorepo__tfmodules_load_balancer # 2020-10-19T13:34:37+05:30 - Add gitignore
monorepo__rebase_it "49d0f86" monorepo__tfmodules_redis # 2020-10-19T13:39:29+05:30 - Update README.md
monorepo__rebase_it "9de6dec" monorepo__tfmodules_iam_terraform_role # 2020-10-19T13:40:39+05:30 - Update README.md
monorepo__rebase_it "228447f" monorepo__tfmodules_iam_shell_role # 2020-10-19T13:41:25+05:30 - Update README.md
monorepo__rebase_it "94725fc" monorepo__tfmodules_iam_access_role # 2020-10-19T13:43:06+05:30 - Update README
monorepo__rebase_it "3a18c5c" monorepo__tfmodules_autoscaling_group # 2020-10-19T13:44:06+05:30 - Update README
monorepo__rebase_it "f5aa746" monorepo__tfmodules_deployment # 2020-10-19T13:45:34+05:30 - Update README
monorepo__rebase_it "0257994" monorepo__tfmodules_database # 2020-10-19T13:46:12+05:30 - Update README
monorepo__rebase_it "0e7da46" monorepo__tfmodules_cloudwatch_slack_notifications # 2020-10-19T13:47:44+05:30 - Update README
monorepo__rebase_it "4d26040" monorepo__tfmodules_cloudwatch # 2020-10-20T11:05:13+02:00 - fix dashboard index wrap
monorepo__rebase_it "65e1b5a" monorepo__tfmodules_static_website # 2020-11-03T11:54:09+01:00 - List params
monorepo__rebase_it "160f87a" monorepo__tfmodules_cloudwatch_agent_conf # 2020-12-08T09:25:01+01:00 - Update configuration with user data
monorepo__rebase_it "8d16220" monorepo__tfmodules_deployment # 2021-01-16T03:19:31+01:00 - INFRA-1308: updated suspend_asg lambda
monorepo__rebase_it "9e28960" monorepo__tfmodules_database # 2021-01-18T11:12:28-03:00 - INFRA-1052: Remove provider from module.
monorepo__rebase_it "9d2feb8" monorepo__tfmodules_deployment # 2021-02-11T00:27:33+01:00 - Merge branch 'master' into infra_1391
monorepo__rebase_it "2852f53" monorepo__tfmodules_instance # 2021-02-26T16:39:11-03:00 - Add availability_zone to aws_instance (that matches the one for EBS volume).
monorepo__rebase_it "8b997a1" monorepo__tfmodules_deployment # 2021-03-02T08:28:46+01:00 - Change channel for task
monorepo__rebase_it "96b84a8" monorepo__tfmodules_instance # 2021-03-10T12:20:21+01:00 - Run fmt, fix variable name in EBS mount
monorepo__rebase_it "bc82cff" monorepo__tfmodules_ftp   # 2021-03-10T13:38:43-03:00 - Initial commit.
monorepo__rebase_it "8ae1443" monorepo__tfmodules_instance # 2021-03-10T13:45:27-03:00 - Create configuration files for proftpd.
monorepo__rebase_it "c2636f7" monorepo__tfmodules_ftp   # 2021-03-10T18:05:50-03:00 - Output domain name and add s3_enable variable.
monorepo__rebase_it "8528430" monorepo__tfmodules_instance # 2021-03-11T14:46:01-03:00 - Add configure_redash.
monorepo__rebase_it "15a3ae9" monorepo__tfmodules_ftp   # 2021-03-17T12:50:14-03:00 - Add support for create_ftp_user_roles.
monorepo__rebase_it "3891108" monorepo__tfmodules_instance # 2021-03-24T12:08:57-03:00 - Use /opt/motoinsight/utils.sh if available.
monorepo__rebase_it "6e2838c" monorepo__tfmodules_ftp   # 2021-03-24T12:09:51-03:00 - Update tfmodule-instance (with support for utils.sh).
monorepo__rebase_it "fdd09e4" monorepo__tfmodules_instance # 2021-03-24T13:48:02-03:00 - Fix syntax-error.
monorepo__rebase_it "dc85b97" monorepo__tfmodules_ftp   # 2021-03-31T08:02:59+02:00 - INFRA-1414 Proper name in permissions
monorepo__rebase_it "2e83505" monorepo__tfmodules_instance # 2021-04-23T16:07:38-03:00 - Add functions for user_data.sh.
monorepo__rebase_it "c5d9a29" monorepo__tfmodules_redis # 2021-04-26T07:07:59+02:00 - Add suffix to allow multiple redis instances
monorepo__rebase_it "b493028" monorepo__tfmodules_database # 2021-04-26T15:55:47-03:00 - Merge pull request #2 from unhaggle/infra_1375
monorepo__rebase_it "ed4deee" monorepo__tfmodules_instance # 2021-04-28T10:38:12-03:00 - Use updated utils.sh.
monorepo__rebase_it "c5acc3d" monorepo__tfmodules_redis # 2021-05-03T07:28:41+02:00 - Add endpoint and multi az
monorepo__rebase_it "2d60c22" monorepo__tfmodules_ftp   # 2021-05-13T16:28:39-03:00 - Add ami_version parameter.
monorepo__rebase_it "4d61488" monorepo__tfmodules_instance # 2021-05-17T10:28:32-03:00 - The option iam_policies now expects full ARN.
monorepo__rebase_it "cfebff2" monorepo__tfmodules_ftp   # 2021-05-19T15:11:36-03:00 - FIX: Cron jobs must be executed by app-user and fix ACL permission for uploaded files.
monorepo__rebase_it "8c0ce92" monorepo__tfmodules_instance # 2021-05-19T15:11:56-03:00 - FIX: Cron jobs must be executed by app-user.
monorepo__rebase_it "253bedc" monorepo__tfmodules_ftp   # 2021-05-24T13:42:22-03:00 - Add sync-ftp.sh and gen_passwd.py scripts to this repo.
monorepo__rebase_it "a8c14e6" monorepo__tfmodules_cloudwatch # 2021-05-25T12:52:13+02:00 - INFRA-1551: Added celery module that by default creates scale up and scale down alarms
monorepo__rebase_it "0b179f9" monorepo__tfmodules_instance # 2021-05-25T17:36:43-03:00 - Add skip_destroy to volume attachment option.
monorepo__rebase_it "0c94e81" monorepo__tfmodules_ftp   # 2021-05-25T17:38:25-03:00 - Add skip_destroy to volume attachment option.
monorepo__rebase_it "cfd6857" monorepo__tfmodules_cloudwatch # 2021-05-25T18:26:06+02:00 - INFRA-1551: Changes due to wrong for_each definition
monorepo__rebase_it "ab90286" monorepo__tfmodules_instance # 2021-05-26T16:50:16-03:00 - Replace cron_jobs with crontab parameter.
monorepo__rebase_it "9433f5d" monorepo__tfmodules_ftp   # 2021-05-26T16:51:31-03:00 - Replace cron_jobs with crontab parameter.
monorepo__rebase_it "e44304f" monorepo__tfmodules_instance # 2021-06-18T17:40:10-03:00 - Add user_data_functions parameter.
monorepo__rebase_it "d6669c8" monorepo__tfmodules_autoscaling_group # 2021-07-05T11:15:24+02:00 - Merge pull request #1 from unhaggle/infra_1479
monorepo__rebase_it "9b6d856" monorepo__tfmodules_database # 2021-07-23T11:48:35-03:00 - Add performance_insights_enabled and monitoring_interval options. (#3)
monorepo__rebase_it "17915f5" monorepo__tfmodules_ec2_alerts # 2021-07-30T13:20:41+02:00 - fix lambda template
monorepo__rebase_it "17909f8" monorepo__tfmodules_instance # 2021-07-30T14:26:27-03:00 - Add support to create the instance inside a VPC (subnet_id).
monorepo__rebase_it "aaa4224" monorepo__tfmodules_ami_build # 2021-08-02T15:14:46-03:00 - Initial commit (working).
monorepo__rebase_it "ebb5737" monorepo__tfmodules_ftp   # 2021-08-02T16:34:01-03:00 - Update tfmodule-instance version.
monorepo__rebase_it "ed4405a" monorepo__tfmodules_ec2_alerts # 2021-08-19T08:33:19+02:00 - fix return type
monorepo__rebase_it "b24b21e" monorepo__tfmodules_load_balancer # 2021-09-10T15:36:44-03:00 - Add support for multiple copies in the same project.
monorepo__rebase_it "1ee2b5c" monorepo__tfmodules_instance # 2021-09-24T14:40:30-03:00 - FIX: Fix logdna-agent environment parameter.
monorepo__rebase_it "8a6665b" monorepo__tfmodules_newrelic_stream # 2021-10-08T15:55:29+02:00 - update README
monorepo__rebase_it "5468df3" monorepo__tfmodules_ftp   # 2021-10-14T13:03:58-03:00 - FIX: Fix allow outbound for FTP instance.
monorepo__rebase_it "401a2c9" monorepo__tfmodules_autoscaling_group # 2021-10-15T13:09:08+02:00 - Merge pull request #3 from unhaggle/enable_tags
monorepo__rebase_it "1085c9b" monorepo__tfmodules_instance # 2021-10-19T14:34:07-03:00 - FIX: Always create the instance in a VPC. Either default one or given one.
monorepo__rebase_it "40c188f" monorepo__tfmodules_ftp   # 2021-10-19T14:36:23-03:00 - Update tfmodule-instance.
monorepo__rebase_it "f5d3999" monorepo__tfmodules_load_balancer # 2021-11-01T17:27:00-03:00 - v2.1.0: Add access-logs, health_check_path and target_type options.
monorepo__rebase_it "0b0e36f" monorepo__tfmodules_mi_iam_roles # 2022-01-20T15:45:53+01:00 - add trader scoped access
monorepo__rebase_it "229a7bb" monorepo__tfmodules_autoscaling_group # 2022-02-16T11:10:23-03:00 - Change termination policy to add OldInstance before Default.
monorepo__rebase_it "5640319" monorepo__tfmodules_mi_iam_roles # 2022-03-04T15:57:39+01:00 - add kms access to scoped role
monorepo__rebase_it "4b73fa1" monorepo__tfmodules_autoscaling_group # 2022-03-08T13:51:01-03:00 - INFRA-1890: Update Terraform AWS provider. (#4)
monorepo__rebase_it "34c723c" monorepo__tfmodules_redis # 2022-03-08T13:51:08-03:00 - INFRA-1890: Update Terraform AWS provider. (#2)
monorepo__rebase_it "eaba9c4" monorepo__tfmodules_database # 2022-03-08T13:53:34-03:00 - Add CHANGELOG.md
monorepo__rebase_it "025958e" monorepo__tfmodules_redis # 2022-03-08T13:56:35-03:00 - Add CHANGELOG.md
monorepo__rebase_it "100b944" monorepo__tfmodules_autoscaling_group # 2022-03-08T14:04:01-03:00 - Add CHANGELOG.md
monorepo__rebase_it "f180d19" monorepo__tfmodules_newrelic_stream # 2022-03-08T17:39:34-03:00 - INFRA-1890: Update Terraform AWS provider.
monorepo__rebase_it "21930b0" monorepo__tfmodules_s3_bucket # 2022-03-09T15:19:13-03:00 - ADD: S3 bucket policy is optional (default: false).
monorepo__rebase_it "c693a8a" monorepo__tfmodules_redis # 2022-03-11T12:04:19-03:00 - Add extra variables to match current deployed resources.
monorepo__rebase_it "fa22a50" monorepo__tfmodules_instance # 2022-03-29T21:08:52-03:00 - Added psql_version.
monorepo__rebase_it "0b6e0c0" monorepo__tfmodules_s3_bucket # 2022-04-04T13:49:34-03:00 - Update README.md.
monorepo__rebase_it "9a0babd" monorepo__tfmodules_redash # 2022-04-05T16:10:39-03:00 - Add REDASH_MAIL configuration via Parameter Store.
monorepo__rebase_it "819ec4b" monorepo__tfmodules_instance # 2022-04-07T16:36:04-03:00 - Add user_data_filepath.
monorepo__rebase_it "da296be" monorepo__tfmodules_redash # 2022-04-07T16:37:47-03:00 - Add custom user_data.sh to configure redash using AWS Parameter Store (/opt/redash/env).
monorepo__rebase_it "f9f1a7c" monorepo__tfmodules_instance # 2022-04-19T08:57:45-03:00 - Add volume_device_mount.
monorepo__rebase_it "1458997" monorepo__tfmodules_redash # 2022-04-19T11:24:55-03:00 - Add readme.
monorepo__rebase_it "ec37c99" monorepo__tfmodules_mi_iam_roles # 2022-04-22T10:39:48+02:00 - admin full access convertus and motoinsight
monorepo__rebase_it "116ea8f" monorepo__tfmodules_auto_deploy # 2022-05-24T10:31:38-03:00 - First commit.
monorepo__rebase_it "b069bbd" monorepo__tfmodules_redash # 2022-05-26T10:19:41-03:00 - Replace instance when changing use_data.
monorepo__rebase_it "16f7cb1" monorepo__tfmodules_instance # 2022-05-26T10:46:55-03:00 - Add user_data_extra_vars.
monorepo__rebase_it "1370b2f" monorepo__tfmodules_redash # 2022-05-26T17:15:48-03:00 - Use extra_vars as a map on user_data.
monorepo__rebase_it "02bb5c3" monorepo__tfmodules_auto_deploy # 2022-05-27T14:06:16-03:00 - Remove commented code.
monorepo__rebase_it "4be51dc" monorepo__tfmodules_mi_iam_roles # 2022-05-27T16:05:38-03:00 - Replace managed_policy_arns with policy_attachments.
monorepo__rebase_it "9d4142c" monorepo__tfmodules_newrelic_stream # 2022-05-27T17:15:39-03:00 - The resource aws_iam_policy_attachment removes all other policies from the roles.
monorepo__rebase_it "f685725" monorepo__tfmodules_auto_deploy # 2022-06-10T09:07:28-03:00 - Add permission to redeploy RDS instances.
monorepo__rebase_it "d9e59fd" monorepo__tfmodules_autoscaling_group # 2022-06-10T10:24:51+02:00 - support global tags
monorepo__rebase_it "e852ec4" monorepo__tfmodules_auto_deploy # 2022-06-14T10:08:48-03:00 - More permissions.
monorepo__rebase_it "84760fc" monorepo__tfmodules_cloudwatch_slack_notifications # 2022-06-15T13:17:22+02:00 - notify teams
monorepo__rebase_it "14edb9e" monorepo__tfmodules_database # 2022-06-16T14:09:33+02:00 - Merge branch 'infra_1818'
monorepo__rebase_it "85c378c" monorepo__tfmodules_load_balancer # 2022-06-23T16:14:00-03:00 - Add option blackhole_suffix.
monorepo__rebase_it "5456441" monorepo__tfmodules_auto_deploy # 2022-06-24T16:29:12-03:00 - Add ec2:AttachVolume permision.
monorepo__rebase_it "088d500" monorepo__tfmodules_newrelic_load_balancer_logs # 2022-07-08T18:58:20+02:00 - INFRA-1819: Updated readme once again
monorepo__rebase_it "cdd0034" monorepo__tfmodules_ssm_user # 2022-07-20T11:26:38+02:00 - allow resume and terminate session for user
monorepo__rebase_it "9de26d4" monorepo__tfmodules_mi_iam_roles # 2022-07-21T17:00:51+02:00 - add tenable trust
monorepo__rebase_it "93b5198" monorepo__tfmodules_auto_deploy # 2022-08-01T16:42:23+02:00 - add more permissions
monorepo__rebase_it "9f13418" monorepo__tfmodules_mi_iam_roles # 2022-08-02T17:54:00+02:00 - replace aws_iam_policy_attachment
monorepo__rebase_it "09fe5ab" monorepo__tfmodules_auto_deploy # 2022-08-03T13:22:36-03:00 - Add permissions specific for configurations bucket.
monorepo__rebase_it "5b44504" monorepo__tfmodules_cloudwatch_alarms # 2022-08-16T15:09:17-03:00 - Initial release.
monorepo__rebase_it "aca4bdd" monorepo__tfmodules_autoscaling_group # 2022-08-17T10:25:12-03:00 - Remove deprecated attribute 'tags' from 'aws_autoscaling_group'.
monorepo__rebase_it "aebacd4" monorepo__tfmodules_instance # 2022-08-18T18:29:00-03:00 - Add private_ip output.
monorepo__rebase_it "19b9ab9" monorepo__tfmodules_redash # 2022-08-18T18:30:48-03:00 - Add private_ip output.
monorepo__rebase_it "e0789dd" monorepo__tfmodules_ssm_user # 2022-08-22T09:06:05-03:00 - Fix ec2:DescribeInstance permission.
monorepo__rebase_it "e318791" monorepo__tfmodules_auto_deploy # 2022-08-24T12:23:22-03:00 - Add permission ec2:DescribeNatGateway.
monorepo__rebase_it "1ef2a14" monorepo__tfmodules_cloudwatch_alarms # 2022-08-25T14:30:21-03:00 - Fix s3-object filename.
monorepo__rebase_it "d4033bf" monorepo__tfmodules_s3_bucket # 2022-08-31T13:30:24-03:00 - Add support for website.
monorepo__rebase_it "d3f6bb0" monorepo__tfmodules_load_balancer # 2022-09-13T12:53:58-03:00 - Add vpc_id output.
monorepo__rebase_it "ce0cb01" monorepo__tfmodules_flower # 2022-09-13T12:58:10-03:00 - Initial commit.
monorepo__rebase_it "f5fefe4" monorepo__tfmodules_instance # 2022-09-13T13:04:48-03:00 - FIX function configure_logdna_agent to support environment variables with prefix.
monorepo__rebase_it "741237c" monorepo__tfmodules_flower # 2022-09-13T13:05:23-03:00 - Update tfmodule-instance to support environment variables with prefix.
monorepo__rebase_it "b2e0969" monorepo__tfmodules_cloudwatch_slack_notifications # 2022-09-20T16:39:06+02:00 - INFRA-2034: Bumped other lambdas nodejs
monorepo__rebase_it "27675f0" monorepo__tfmodules_auto_deploy # 2022-09-21T09:54:31-03:00 - Add mandatory 'configuration_bucket' parameter.
monorepo__rebase_it "a43d4b4" monorepo__tfmodules_cloudwatch_slack_notifications # 2022-09-27T18:34:09+02:00 - INFRA-2034: Added changelog
monorepo__rebase_it "044964c" monorepo__tfmodules_flower # 2022-09-28T16:10:31-03:00 - Add basic auth.
monorepo__rebase_it "21ca7c5" monorepo__tfmodules_cloudwatch_slack_notifications # 2022-10-04T16:44:58+02:00 - INFRA-2034: Make lambda runtime as variable with default_value
monorepo__rebase_it "cb49709" monorepo__tfmodules_autoscaling_group # 2022-10-17T12:06:01+02:00 - INFRA-2055: require session tokens for metadata service
monorepo__rebase_it "3ca795d" monorepo__tfmodules_s3_bucket # 2022-10-24T13:02:53-03:00 - Fix iam_policy_document name.
monorepo__rebase_it "8e144f7" monorepo__tfmodules_auto_deploy # 2022-10-27T17:43:24+02:00 - update autodeploy permissions
monorepo__rebase_it "541d010" monorepo__tfmodules_cloudwatch_alarms # 2022-10-29T13:32:50-03:00 - Add configuration_path variable.
monorepo__rebase_it "fb29c1f" monorepo__tfmodules_cloudwatch_slack_notifications # 2022-11-07T16:25:54+01:00 - Merge pull request #2 from unhaggle/infra_2063
monorepo__rebase_it "0edb559" monorepo__tfmodules_load_balancer # 2022-11-18T08:46:33-03:00 - Minor fixes.
monorepo__rebase_it "4457d12" monorepo__tfmodules_redash # 2022-11-22T18:13:03-03:00 - ADD: Add name and listener_priority variables.
monorepo__rebase_it "d549e1e" monorepo__tfmodules_database # 2022-11-24T10:19:53+01:00 - extend rds io read and write evaluation period to alert
monorepo__rebase_it "545ef7c" monorepo__tfmodules_auto_deploy # 2022-11-29T09:58:23-03:00 - Apply terraform fmt.
monorepo__rebase_it "769fc86" monorepo__tfmodules_autoscaling_group # 2022-12-02T10:09:07+01:00 - http_endpoint enabled by default
monorepo__rebase_it "72f863f" monorepo__tfmodules_redash # 2023-01-06T14:26:09-03:00 - Add option enable_secret_key and apply FMT.
monorepo__rebase_it "673db16" monorepo__tfmodules_redis # 2023-01-06T14:49:47-03:00 - Change the name of the TF file to tfmodule-redis.tf.
monorepo__rebase_it "7284bf6" monorepo__tfmodules_ami_build # 2023-01-06T14:50:02-03:00 - Change the name of the TF file to tfmodule-ami_build.tf.
monorepo__rebase_it "6cbc9ed" monorepo__tfmodules_instance # 2023-01-13T10:14:45+01:00 - Merge branch 'infra_2083' of github.com:unhaggle/tfmodule-instance
monorepo__rebase_it "3cc0be4" monorepo__tfmodules_flower # 2023-01-19T08:36:35-03:00 - Purge offline workers.
monorepo__rebase_it "811dec8" monorepo__tfmodules_ftp   # 2023-02-03T10:15:05-03:00 - Add option to create the FTP instances in a VPC.
monorepo__rebase_it "20a919f" monorepo__tfmodules_load_balancer # 2023-02-09T12:05:54-03:00 - Review name variables.
monorepo__rebase_it "96abc31" monorepo__tfmodules_ssm_user # 2023-02-22T16:50:54-03:00 - Fix required_version.
monorepo__rebase_it "4552004" monorepo__tfmodules_autoscaling_group # 2023-02-24T14:26:51-03:00 - INFRA-2142: Add option ec2_volume_encrypted.
monorepo__rebase_it "9cb63b2" monorepo__tfmodules_instance # 2023-02-24T14:56:49-03:00 - INFRA-2141: Ensure EBS volumes have a corresponding snapshot.
monorepo__rebase_it "207cf6c" monorepo__tfmodules_ftp   # 2023-02-24T15:06:45-03:00 - Add psql version option (now mandatory by tfmodule-instance).
monorepo__rebase_it "f3d625a" monorepo__tfmodules_ami_build # 2023-02-27T13:39:35-03:00 - Add permissions to KSM, SSM and S3 buckets.
monorepo__rebase_it "c108e68" monorepo__tfmodules_instance # 2023-03-02T09:03:01-03:00 - INFRA-2027: terrascan fixes (still have 1H).
monorepo__rebase_it "ac2b05a" monorepo__tfmodules_ftp   # 2023-03-02T09:26:38-03:00 - Update tfmodule-instance version with tennable fixes and ignore some issues with terrascan.
monorepo__rebase_it "b11d494" monorepo__tfmodules_instance # 2023-03-02T10:00:33-03:00 - Add encrypt_volumes option.
monorepo__rebase_it "23adc2b" monorepo__tfmodules_ftp   # 2023-03-02T10:02:23-03:00 - Add encrypt_volumes option.
monorepo__rebase_it "f054321" monorepo__tfmodules_flower # 2023-03-02T10:15:09-03:00 - Encrypt EBS volumes.
monorepo__rebase_it "170edea" monorepo__tfmodules_instance # 2023-03-03T11:08:24+01:00 - INFRA-2055: instance metadata optional
monorepo__rebase_it "ddbfc11" monorepo__tfmodules_database # 2023-03-06T15:39:08+01:00 - INFRA-1790: move alerts to newrelic
monorepo__rebase_it "527583c" monorepo__tfmodules_cloudwatch # 2023-03-08T10:21:39+01:00 - INFRA-1790: drop cloudwatch dashboard
monorepo__rebase_it "642911c" monorepo__tfmodules_s3_bucket # 2023-03-10T18:20:03+01:00 - fix default public path
monorepo__rebase_it "d67e0c1" monorepo__tfmodules_ftp   # 2023-03-13T10:54:20-03:00 - Accept metadata without tokens (required by flower and fpt).
monorepo__rebase_it "017f01f" monorepo__tfmodules_flower # 2023-03-13T10:56:45-03:00 - Accept metadata without tokens (required by flower and fpt).
monorepo__rebase_it "c117dfb" monorepo__tfmodules_instance # 2023-03-13T11:18:53-03:00 - ADD: Add separated option for encrypt_root_volume and encrypt_extra_volume.
monorepo__rebase_it "0054a92" monorepo__tfmodules_ftp   # 2023-03-13T11:20:09-03:00 - ADD: Add separated option for encrypt_root_volume and encrypt_extra_volume.
monorepo__rebase_it "54e8f56" monorepo__tfmodules_instance # 2023-03-13T11:59:05-03:00 - Update CHANGELOG.
monorepo__rebase_it "604ced3" monorepo__tfmodules_ftp   # 2023-03-13T12:00:08-03:00 - Update CHANGELOG.
monorepo__rebase_it "2838ec6" monorepo__tfmodules_flower # 2023-03-13T12:13:50-03:00 - FIX celery flower command line typo.
monorepo__rebase_it "893d3ec" monorepo__tfmodules_s3_bucket # 2023-03-14T18:48:56+01:00 - add super-public policy
monorepo__rebase_it "d497922" monorepo__tfmodules_flower # 2023-03-16T14:35:31-03:00 - Fix flower listener priority.
monorepo__rebase_it "53d6366" monorepo__tfmodules_instance # 2023-03-16T17:21:00-03:00 - Increased aws_ebs_snapshot timeouts (2h).
monorepo__rebase_it "8c2a2d4" monorepo__tfmodules_ftp   # 2023-03-16T17:22:07-03:00 - Increased aws_ebs_snapshot timeouts (2h).
monorepo__rebase_it "c74d784" monorepo__tfmodules_newrelic_load_balancer_logs # 2023-03-17T11:49:31+01:00 - update lambda version
monorepo__rebase_it "297183b" monorepo__tfmodules_ecs_cluster # 2023-03-20T15:09:38-03:00 - Add missing submodules.
monorepo__rebase_it "6830372" monorepo__tfmodules_ecs_taskdef # 2023-03-20T15:13:24-03:00 - Initial commit.
monorepo__rebase_it "23ef57a" monorepo__tfmodules_ecs_cluster # 2023-03-20T15:14:59-03:00 - Use publised tfmodule-ecs_taskdef.
monorepo__rebase_it "0785057" monorepo__tfmodules_iam   # 2023-03-20T15:18:25-03:00 - Initial commit.
monorepo__rebase_it "15896fb" monorepo__tfmodules_ecs_taskdef # 2023-03-20T15:19:24-03:00 - Use publised tfmodule-iam.
monorepo__rebase_it "bec5965" monorepo__tfmodules_ecs_service # 2023-03-20T15:29:08-03:00 - Initial commit.
monorepo__rebase_it "3b805b7" monorepo__tfmodules_efs   # 2023-03-20T15:32:09-03:00 - Initial commit.
monorepo__rebase_it "34bf190" monorepo__tfmodules_ecs_cluster # 2023-03-20T15:34:14-03:00 - Creating all required tfmodules.
monorepo__rebase_it "586b91c" monorepo__tfmodules_redash # 2023-03-21T14:29:19-03:00 - Add encryption to both root and extra volumes.
monorepo__rebase_it "3dda6de" monorepo__tfmodules_s3_bucket # 2023-03-23T10:02:46+01:00 - create versioning only if enabled
monorepo__rebase_it "a80b511" monorepo__tfmodules_redis # 2023-03-23T10:58:27-03:00 - REFACTOR: Simplify redis module adapting to current standards.
monorepo__rebase_it "48350c5" monorepo__tfmodules_s3_bucket # 2023-03-23T14:31:29+01:00 - extendable private policy actions
monorepo__rebase_it "8dc145b" monorepo__tfmodules_redis # 2023-03-24T08:24:20-03:00 - Add note about in-trasit encryption.
monorepo__rebase_it "444a266" monorepo__tfmodules_instance # 2023-03-24T14:02:17-03:00 - Add option volume_snapshot_id.
monorepo__rebase_it "7071983" monorepo__tfmodules_ftp   # 2023-03-24T14:04:04-03:00 - Add option volume_snapshot_id.
monorepo__rebase_it "fc43cce" monorepo__tfmodules_instance # 2023-03-24T14:11:09-03:00 - Rename encryption options.
monorepo__rebase_it "1e271f2" monorepo__tfmodules_ftp   # 2023-03-24T14:12:43-03:00 - Rename encryption options.
monorepo__rebase_it "c9dc50c" monorepo__tfmodules_newrelic_stream # 2023-03-24T15:13:27+01:00 - add backup bucket versioning
monorepo__rebase_it "0db823b" monorepo__tfmodules_redash # 2023-03-27T10:46:41-03:00 - Add volume_snapshot_id option.
monorepo__rebase_it "b4e83d9" monorepo__tfmodules_instance # 2023-03-27T11:11:46-03:00 - Add volume_snapshot_timeout option.
monorepo__rebase_it "76ddd65" monorepo__tfmodules_ftp   # 2023-03-27T11:26:23-03:00 - Add option volume_snapshot_enabled.
monorepo__rebase_it "3244941" monorepo__tfmodules_redash # 2023-03-27T11:52:02-03:00 - Add volume_snapshot_enabled option.
monorepo__rebase_it "39c30e3" monorepo__tfmodules_ecs_service # 2023-03-27T12:21:34-03:00 - Rename terraform file to match current standards.
monorepo__rebase_it "5e67607" monorepo__tfmodules_ecs_cluster # 2023-03-29T11:53:17-03:00 - User our version of oidc-github module that fixes a small issue.
monorepo__rebase_it "b240440" monorepo__tfmodules_auto_deploy # 2023-03-29T12:10:03-03:00 - Use aws_iam_policy_document.
monorepo__rebase_it "9c88149" monorepo__tfmodules_database # 2023-03-29T12:11:57-03:00 - Add optional option.
monorepo__rebase_it "60f8c87" monorepo__tfmodules_autoscaling_group # 2023-03-29T12:13:45-03:00 - Update desciptions and CHANGELOG.
monorepo__rebase_it "97dc9ed" monorepo__tfmodules_ecs_service # 2023-03-31T13:50:18-03:00 - Add ecr_repository option to ecs-cluster.
monorepo__rebase_it "410a8eb" monorepo__tfmodules_ecs_taskdef # 2023-03-31T13:50:43-03:00 - Add permissions to read from ECR repository.
monorepo__rebase_it "3f9d54c" monorepo__tfmodules_ecs_cluster # 2023-03-31T13:52:14-03:00 - Remove tfmodules subdirectory.
monorepo__rebase_it "ad5650a" monorepo__tfmodules_autoscaling_group # 2023-04-04T14:23:29-03:00 - Reorganize files.
monorepo__rebase_it "5656845" monorepo__tfmodules_ecs_cluster # 2023-04-04T14:31:29-03:00 - Remove enable_metrics.
monorepo__rebase_it "3a4e9f6" monorepo__tfmodules_redis # 2023-04-04T20:49:52-03:00 - Backward compatibility.
monorepo__rebase_it "e039872" monorepo__tfmodules_s3_bucket # 2023-04-05T10:36:31-03:00 - Accepts acl=null (new default value).
monorepo__rebase_it "dbb9bf8" monorepo__tfmodules_database # 2023-04-10T10:49:22-03:00 - Add custom parameters for replica.
monorepo__rebase_it "a460d69" monorepo__tfmodules_redis # 2023-04-10T15:21:48-03:00 - Remove all 'try' calls.
monorepo__rebase_it "1e1571b" monorepo__tfmodules_autoscaling_group # 2023-04-12T11:05:14-03:00 - Refatory to acomodate Tenable issues.
monorepo__rebase_it "e699281" monorepo__tfmodules_load_balancer # 2023-04-14T10:40:07-03:00 - Merge branch 'v3.x'
monorepo__rebase_it "01ab2ab" monorepo__tfmodules_cloudwatch # 2023-04-14T12:33:55+02:00 - drop lb target response high alert
monorepo__rebase_it "4a661b6" monorepo__tfmodules_flower # 2023-04-14T13:15:20-03:00 - WIP: Support setting the cloudflare_register value to use an alias instead of the load-balancer internal URL.
monorepo__rebase_it "7c21b6a" monorepo__tfmodules_database # 2023-04-17T16:45:31-03:00 - Apply format.
monorepo__rebase_it "1824335" monorepo__tfmodules_newrelic_stream # 2023-04-26T09:44:20-03:00 - Add encryption to backup s3 bucket.
monorepo__rebase_it "cb612f8" monorepo__tfmodules_iam   # 2023-04-26T09:47:43-03:00 - Reorgnize code.
monorepo__rebase_it "4116054" monorepo__tfmodules_database # 2023-04-26T09:49:46-03:00 - Set storage_encrypted option when kms_key_id is set.
monorepo__rebase_it "974f90f" monorepo__tfmodules_auto_deploy # 2023-05-23T12:10:27-03:00 - Add ec2:MonitorInstances permissions.
monorepo__rebase_it "b95ccf9" monorepo__tfmodules_database # 2023-05-26T13:40:49-03:00 - Add iam_database_authenticaiont_enhabled (tenable).
monorepo__rebase_it "2895673" monorepo__tfmodules_ecs_cluster # 2023-06-22T16:26:12-03:00 - Add options 'repositories' and 'autoscaling_policies'.
monorepo__rebase_it "89fe5be" monorepo__tfmodules_ecs_taskdef # 2023-06-22T16:28:12-03:00 - Minor name and format changes.
monorepo__rebase_it "2a1272d" monorepo__tfmodules_iam   # 2023-06-23T00:24:04-03:00 - Rename parameter to policies.
monorepo__rebase_it "6082955" monorepo__tfmodules_ecs_cluster # 2023-06-23T00:25:29-03:00 - Add option to give roles the autoscaling can assume.
monorepo__rebase_it "11fbb89" monorepo__tfmodules_instance # 2023-07-11T10:15:59-03:00 - Add key_name parameter.
monorepo__rebase_it "84e1d54" monorepo__tfmodules_ftp   # 2023-07-21T13:00:39-03:00 - Minor format changes.
monorepo__rebase_it "ed8d063" monorepo__tfmodules_ecs_taskdef # 2023-07-21T13:05:14-03:00 - Add assume_roles and iam_policies (removed extra_iam_policies).
monorepo__rebase_it "2fcfb75" monorepo__tfmodules_redash # 2023-11-03T11:38:06+01:00 - add custom docker-compose file
monorepo__rebase_it "e5eeeed" monorepo__tfmodules_ecs_taskdef # 2023-11-07T10:04:39-03:00 - Use tfmodule from tdr-autosync.
monorepo__rebase_it "d7ccaad" monorepo__tfmodules_ecs_cluster # 2023-11-07T10:06:56-03:00 - Use tfmodule from tdr-autosync.
monorepo__rebase_it "1f20048" monorepo__tfmodules_s3_bucket # 2023-12-01T11:30:27-03:00 - Update version constrains for cloudflare and aws providers.
monorepo__rebase_it "da3a727" monorepo__tfmodules_redash # 2023-12-01T11:46:24-03:00 - Update version constrains for cloudflare and aws providers.
monorepo__rebase_it "7e8e48e" monorepo__tfmodules_cloudwatch # 2023-12-01T12:56:09-03:00 - Update version constrains for cloudflare and aws providers.
monorepo__rebase_it "e2e8b9e" monorepo__tfmodules_ssm_user # 2023-12-01T12:58:07-03:00 - Update version constrains for cloudflare and aws providers.
monorepo__rebase_it "f6f7868" monorepo__tfmodules_flower # 2023-12-01T13:01:07-03:00 - Update version constrains for cloudflare and aws providers.
monorepo__rebase_it "2485229" monorepo__tfmodules_iam   # 2023-12-01T13:01:25-03:00 - Update version constrains for cloudflare and aws providers.
monorepo__rebase_it "fdeb209" monorepo__tfmodules_ecs_service # 2023-12-01T13:01:44-03:00 - Update version constrains for cloudflare and aws providers.
monorepo__rebase_it "455dd67" monorepo__tfmodules_ftp   # 2023-12-01T13:01:55-03:00 - Update version constrains for cloudflare and aws providers.
monorepo__rebase_it "2364fa8" monorepo__tfmodules_flower # 2023-12-06T16:00:06-03:00 - Load environment variables correctly.
monorepo__rebase_it "03c525a" monorepo__tfmodules_newrelic_stream # 2023-12-07T09:01:07-03:00 - Support AWS provider version 5.X.
monorepo__rebase_it "87d9aff" monorepo__tfmodules_flower # 2023-12-07T09:12:45-03:00 - Release.
monorepo__rebase_it "56d9225" monorepo__tfmodules_redis # 2023-12-07T09:14:48-03:00 - Support aws provider 5.X.
monorepo__rebase_it "744ea2c" monorepo__tfmodules_s3_bucket # 2023-12-12T10:57:08-03:00 - Move ensure_tls statement inside other documents.
monorepo__rebase_it "d5d0f6a" monorepo__tfmodules_newrelic_stream # 2023-12-12T11:17:38-03:00 - Fix for Tenable AC_AWS_0646
monorepo__rebase_it "4ce23e6" monorepo__tfmodules_s3_bucket # 2024-01-05T13:27:39-03:00 - Add sid for cloudflare policy.
monorepo__rebase_it "e178b8e" monorepo__tfmodules_redis # 2024-01-09T15:14:59-03:00 - Only set `preferred_cache_cluster_azs` when multi-az is enabled.
monorepo__rebase_it "b907b12" monorepo__tfmodules_redash # 2024-01-19T10:21:19+01:00 - add instance metadata option
monorepo__rebase_it "d3a3d82" monorepo__tfmodules_ftp   # 2023-12-07T09:10:34-03:00 - Release.
monorepo__rebase_it "f883b06" monorepo__tfmodules_cloudwatch_agent_conf # 2024-01-19T16:44:31-03:00 - Add cloudwatch_logs_encryption_key and set default value for cloudwatch_logs_retention_days=90.
monorepo__rebase_it "2a969ad" monorepo__tfmodules_instance # 2024-01-19T16:45:56-03:00 - Add logs_encryption_key.
monorepo__rebase_it "e9fdc54" monorepo__tfmodules_flower # 2024-01-19T17:07:06-03:00 - Add logs retention_days and encryption_key options.
monorepo__rebase_it "22d9e83" monorepo__tfmodules_ftp   # 2024-01-19T17:24:05-03:00 - Add logs retention_days and encryption_key options.
monorepo__rebase_it "3d03411" monorepo__tfmodules_redash # 2024-01-19T17:33:22-03:00 - Add logs retention_days and encryption_key options.
monorepo__rebase_it "e969709" monorepo__tfmodules_flower # 2024-01-22T09:38:44-03:00 - Small refactory. Removed option instance_metadata_options (we always use IDMSv2.
monorepo__rebase_it "8b19c71" monorepo__tfmodules_ftp   # 2024-01-22T09:39:15-03:00 - Small refactory. Removed option instance_metadata_options (we always use IDMSv2).
monorepo__rebase_it "dfe9e39" monorepo__tfmodules_autoscaling_group # 2024-01-24T12:16:08-03:00 - WIP: Adding options for backward compatibility.

monorepo__cleanup

